// i18n.ts: the English text of the lila translation keys we use, under lila's names, so ported code
// keeps lila's i18n.site.someKey lookups. Text from lila's translation/source/site.xml and study.xml
// (master, commit 27ffc8b).
// Trim: lila loads the viewer's language into a global `i18n`, generated by ui/.build/src/i18n.ts.
// We only have English, and no plurals.

// Like lila's I18nFormat: text with a %s placeholder (or %1$s, %2$s, ... for several).
interface I18nFormat {
  (...args: (string | number)[]): string; // the filled-in text
  asArray: <T>(...args: T[]) => (T | string)[]; // for snabbdom, where the args can be VNodes
}

// Like s() and l() in the code that ui/.build/src/i18n.ts generates.
function format(text: string): I18nFormat {
  const f = (...args: (string | number)[]): string => fill(text, ...args).join('');
  f.asArray = <T>(...args: T[]): (T | string)[] => fill(text, ...args);
  return f;
}

// fill('%s was played', x) returns ['', x, ' was played'].
function fill<T>(text: string, ...args: T[]): (T | string)[] {
  const parts: (T | string)[] = text.split(/(%(?:\d\$)?s)/); // the brackets keep the placeholders as parts
  if (args.length) {
    const i = parts.indexOf('%s');
    if (i !== -1) parts[i] = args[0];
    else
      args.forEach((arg, n) => {
        const j = parts.indexOf(`%${n + 1}$s`);
        if (j !== -1) parts[j] = arg;
      });
  }
  return parts;
}

export const i18n = {
  site: {
    bestWasX: format('Best was %s'),
    doItAgain: 'Do it again',
    doneReviewingBlackMistakes: "Done reviewing black's mistakes",
    doneReviewingWhiteMistakes: "Done reviewing white's mistakes",
    evaluatingYourMove: 'Evaluating your move ...',
    findBetterMoveForBlack: 'Find a better move for black',
    findBetterMoveForWhite: 'Find a better move for white',
    learnFromYourMistakes: 'Learn from your mistakes',
    next: 'Next',
    noMistakesFoundForBlack: 'No mistakes found for black',
    noMistakesFoundForWhite: 'No mistakes found for white',
    resumeLearning: 'Resume learning',
    reviewBlackMistakes: "Review black's mistakes",
    reviewWhiteMistakes: "Review white's mistakes",
    skipThisMove: 'Skip this move',
    solution: 'Solution',
    tryAnotherMoveForBlack: 'Try another move for black',
    tryAnotherMoveForWhite: 'Try another move for white',
    viewTheSolution: 'View the solution',
    waitingForAnalysis: 'Waiting for analysis',
    xWasPlayed: format('%s was played'),
    youBrowsedAway: 'You browsed away',
    youCanDoBetter: 'You can do better',
  },
  study: {
    goodMove: 'Good move',
  },
};
