// i18n.ts: the English text of the lila translation keys we use, under lila's names, so ported code
// keeps lila's i18n.site.someKey lookups. Text from lila's translation/source/site.xml and study.xml
// (master, commit 27ffc8b).
// Trim: lila loads the viewer's language into a global `i18n`, generated by ui/.build/src/i18n.ts.
// We only have English.

// Like lila's I18nFormat: text with a %s placeholder (or %1$s, %2$s, ... for several).
interface I18nFormat {
  (...args: (string | number)[]): string; // the filled-in text
  asArray: <T>(...args: T[]) => (T | string)[]; // for snabbdom, where the args can be VNodes
}

// Like s() and l() in the code that ui/.build/src/i18n.ts generates.
function format(text: string): I18nFormat {
  const f = (...args: (string | number)[]): string => fill(text, ...args).join('');
  f.asArray = <T>(...args: T[]): (T | string)[] => fill(text, ...args);
  return f;
}

// Step 8: like lila's I18nPlural: text that depends on a number, like "1 Blunder" / "3 Blunders".
interface I18nPlural {
  (quantity: number, ...args: (string | number)[]): string;
  asArray: <T>(quantity: number, ...args: T[]) => (T | string)[];
}

// Like p() and o() in the code that ui/.build/src/i18n.ts generates. Trim: lila asks the language
// which form a number takes (i18n.quantity); English only has two, 'one' for 1 and 'other'.
function plural(forms: { one: string; other: string }): I18nPlural {
  const pick = (n: number) => (n === 1 ? forms.one : forms.other);
  const f = (n: number, ...args: (string | number)[]): string => fill(pick(n), n, ...args).join('');
  f.asArray = <T>(n: number, ...args: T[]): (T | string)[] => fill(pick(n), ...args);
  return f;
}

// fill('%s was played', x) returns ['', x, ' was played'].
function fill<T>(text: string, ...args: T[]): (T | string)[] {
  const parts: (T | string)[] = text.split(/(%(?:\d\$)?s)/); // the brackets keep the placeholders as parts
  if (args.length) {
    const i = parts.indexOf('%s');
    if (i !== -1) parts[i] = args[0];
    else
      args.forEach((arg, n) => {
        const j = parts.indexOf(`%${n + 1}$s`);
        if (j !== -1) parts[j] = arg;
      });
  }
  return parts;
}

export const i18n = {
  site: {
    accuracy: 'Accuracy',
    advantage: 'Advantage',
    aiNameLevelAiLevel: format('%1$s level %2$s'),
    analysis: 'Analysis board',
    anonymous: 'Anonymous',
    averageCentipawnLoss: 'Average centipawn loss',
    bestWasX: format('Best was %s'),
    blunder: 'Blunder',
    blackDidntMove: "Black didn't move",
    blackIsVictorious: 'Black is victorious',
    blackLeftTheGame: 'Black left the game',
    blackRanOutOfTime: 'Black ran out of time',
    blackResigned: 'Black resigned',
    blitz: 'Blitz',
    bullet: 'Bullet',
    casual: 'Casual',
    cheatDetected: 'Cheat Detected',
    checkmate: 'Checkmate',
    classical: 'Classical',
    computerAnalysis: 'Computer analysis',
    correspondence: 'Correspondence',
    doItAgain: 'Do it again',
    doneReviewingBlackMistakes: "Done reviewing black's mistakes",
    doneReviewingWhiteMistakes: "Done reviewing white's mistakes",
    draw: 'Draw',
    drawClaimed: 'Draw claimed',
    endgame: 'Endgame',
    evaluatingYourMove: 'Evaluating your move ...',
    fiftyMovesWithoutProgress: 'Fifty moves without progress',
    findBetterMoveForBlack: 'Find a better move for black',
    findBetterMoveForWhite: 'Find a better move for white',
    finished: 'Finished',
    flipBoard: 'Flip board',
    inaccuracy: 'Inaccuracy',
    insufficientMaterial: 'Insufficient material',
    learnFromThisMistake: 'Learn from this mistake',
    learnFromYourMistakes: 'Learn from your mistakes',
    menu: 'Menu',
    middlegame: 'Middlegame',
    mistake: 'Mistake',
    next: 'Next',
    noMistakesFoundForBlack: 'No mistakes found for black',
    noMistakesFoundForWhite: 'No mistakes found for white',
    numberBlunders: plural({ one: '%s Blunder', other: '%s Blunders' }),
    numberInaccuracies: plural({ one: '%s Inaccuracy', other: '%s Inaccuracies' }),
    numberMistakes: plural({ one: '%s Mistake', other: '%s Mistakes' }),
    opening: 'Opening',
    resumeLearning: 'Resume learning',
    rapid: 'Rapid',
    rated: 'Rated',
    reviewBlackMistakes: "Review black's mistakes",
    reviewWhiteMistakes: "Review white's mistakes",
    skipThisMove: 'Skip this move',
    solution: 'Solution',
    stalemate: 'Stalemate',
    tryAnotherMoveForBlack: 'Try another move for black',
    tryAnotherMoveForWhite: 'Try another move for white',
    ultraBullet: 'UltraBullet',
    unlimited: 'Unlimited',
    variantEnding: 'Variant ending',
    viewTheSolution: 'View the solution',
    waitingForAnalysis: 'Waiting for analysis',
    whiteDidntMove: "White didn't move",
    whiteIsVictorious: 'White is victorious',
    whiteLeftTheGame: 'White left the game',
    whiteRanOutOfTime: 'White ran out of time',
    whiteResigned: 'White resigned',
    xWasPlayed: format('%s was played'),
    youBrowsedAway: 'You browsed away',
    youCanDoBetter: 'You can do better',
  },
  study: {
    goodMove: 'Good move',
  },
};
